### ISSUE TITLE
Where is the code for Global-to-Global matching? / Why not use pretrained model for TinyFlowNet?

### ISSUE THREAD

**Issue by shoutOutYangJie** [hzxie/RMNet#4]
I want to reproduce your result, and want to know how many GPUs you train the model on?
Thank you.

**Comment by shoutOutYangJie** [comment]
Another question.  Your tiny flownet is also trained. Why not use pretrained model? I mean first training a tiny flownet, and then fixing it when train RMNet.

**Comment by shoutOutYangJie** [comment]
Third question. In your code, you still use global-to-global memory matching.  It is strange.

**Comment by hzxie** [comment]
1. At first, we use 4 1080Ti GPUs. As the memory usage increases (due to the increase of complexity of our method), we use 2 V100 (32GB) GPUs.
2. Actually, the weights of TinyFlowNet are partially borrowed from FlowNet-S and fine-tuned on the precomputed optical flow (See also #3).
3. The matrix multiplication is highly optimized in PyTorch. We implement an extension for local-to-local matching with PyTorch API and CUBLAS, but the speed is lower than the one in PyTorch. Moreover, we find that PyTorch is optimized for our situation where there are lots of zeros in matrices.
